eureka:
  client:
    serviceUrl:
      defaultZone: http://101.132.181.128:8761/eureka/
server:
  port: 8762

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xianliang66/prsirdm/
          searchPaths: config
  application:
    name: config-server